### ISSUE TITLE
UI conflicts

### ISSUE THREAD

**Issue by maxbycode** [Tras/TrasReport#1]
There was no error here, more just suggestions.

When you edit a post, you can change the post ID and still be brought to a editor instead of a "this is not your post therefore you cannot edit it" or "unknown post". 

When you have no friends in the chat UI, the page is completely blank confusing new users (like myself). You should show a 'You need friends before sending messages, go find one' or 'No friends to message with :(' message.

However, this is a very interesting project and I tend to keep up with it in the future. :)

**Comment by HAlexTM** [comment]
Hi, even though you can change the post id, you will not be able to edit a post if this doesn't belong to you
Thanks for the "no friends" suggestion

**Comment by maxbycode** [comment]
I know, but it seems like it will be a lot nicer to just throw an unauthorized message if you know it isn't their post. Unity and such.

**Comment by maxbycode** [comment]
In the share modal, you should also give the direct link for those wanting to share beyond the 5 options you gave.

**Comment by HAlexTM** [comment]
@maxbycode I planned to work on shortened link for the posts (href inside posts), I saw your v0lt project, I would have used link.tras.pw/uid but it's a bit long, can we collaborate​?

**Comment by HAlexTM** [comment]
Done

**Comment by maxbycode** [comment]
@HAlexTM Sure, we can chat about it whenever you can.
