### ISSUE TITLE
Notifications show escaped quotes

### ISSUE THREAD

**Issue by maxbycode** [Tras/TrasReport#2]
#### Did you encounter any code/status error?
No
#### Where did you face this problem?
Chrome Beta, Android 7.1.2 Beta
#### Paste the error here, if any
n/a
#### Additional comments
Unescape or remove the \ from the messages so it appears normal without the random slashes within each message like so:
![image](https://cloud.githubusercontent.com/assets/11779550/24365014/c6b8b38c-12d1-11e7-81ec-453ae07641de.png)

**Comment by HAlexTM** [comment]
fixed
